# Generated by Django 2.2 on 2019-04-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=3)),
                ('residence', models.CharField(max_length=50)),
                ('primary_school', models.CharField(max_length=40)),
                ('high_school', models.CharField(max_length=40)),
                ('university', models.CharField(max_length=40)),
                ('course', models.CharField(max_length=40)),
                ('profession', models.CharField(max_length=30)),
                ('hobbies', models.CharField(max_length=100)),
                ('is_male', models.BooleanField(default=True)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
